project:
  type: website
  output-dir: docs
execute:
  freeze: auto

website:
  twitter-card: true
  open-graph: true
  favicon: arquivos/logo.png
  site-url: "https://gsathler-vi.github.io/"
  site-path: "/"
  image: "preview-image.png"
  page-footer:
    left: "2025, Gabriel Sathler" 
    center: Feito com [Quarto](https://quarto.org/)
    right: 
      - icon: linkedin
        href: "https://www.linkedin.com/in/gabriel-sathler/"
      - icon: github
        href: "https://github.com/gsathler-vi"
      - icon: whatsapp
        href: "https://wa.me/5531998912831"
      - icon: envelope
        href: "mailto:gabrielsathler.vi@gmail.com" 
  title: "Gabriel Sathler"
  navbar:
    tools:
      - icon: linkedin
        href: https://www.linkedin.com/in/gabriel-sathler/
      - icon: github
        href: https://github.com/gsathler-vi
      - icon: whatsapp
        href: https://wa.me/5531998912831
      - icon: envelope
        href: mailto:gabrielsathler.vi@gmail.com
      - icon: three-dots
        menu:
          - text: Lattes
            href:  http://lattes.cnpq.br/9000859452095941
          - text: ORCID
            href:  https://orcid.org/0009-0006-0754-4213
    left:
      - href: index.qmd
        text: Sobre
      - href: experiencia.qmd
        text: Experiência
      - href: certificacoes.qmd
        text: Certificações
      - href: historico.qmd
        text: Histórico Academico
      - href: posts.qmd
        text: Posts
      - href: material.qmd
        text: Materiais e Documentos

format:
  html:
    respect-user-color-scheme: false
    toc: true
    theme:
      light: [cosmo, theme.scss]
      dark: [cosmo, theme-dark.scss]
    code-copy: true
    code-overflow: wrap
    code-fold: true
    code-summary: "Exibir Código"
    css: styles.css
include-in-header:
  - text: "<meta name='viewport' content='width=device-width, initial-scale=1.0'>"